build.gradle, src/main/java/org/myteam/server/ServerApplication.java, src/main/java/org/myteam/server/global/jwt/JwtProperties.java, src/main/java/org/myteam/server/global/jwt/JwtProvider.java, src/main/resources/application.properties, src/main/resources/application.yml
- Jwt 발급, 검증, 인증객체 조회 기능
- Jwt Issuer, secret-key yml 을 통해 가져오도록 개발
- JwtProvider 개발
- applcation.properties -> appliation.yml로 변경
- 유저 role String이 아닌 ENUM으로 관리하도록 변경
=> [CM-33] JwtProvider 개발

build.gradle, src/main/java/org/myteam/server/ServerApplication.java, src/main/java/org/myteam/server/auth/controller/AuthController.java, src/main/java/org/myteam/server/auth/dto/LoginRequestDto.java, src/main/java/org/myteam/server/auth/dto/SignupRequestDto.java, src/main/java/org/myteam/server/auth/dto/TokenResponseDto.java, src/main/java/org/myteam/server/auth/service/AuthService.java, src/main/java/org/myteam/server/auth/test/TestController.java, src/main/java/org/myteam/server/global/config/PasswordEncoderConfig.java, src/main/java/org/myteam/server/global/jwt/JwtProperties.java, src/main/java/org/myteam/server/global/jwt/JwtProvider.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/repository/MemberRepository.java, src/main/resources/application-auth.yml, src/main/resources/application-dev.yml, src/main/resources/application.properties, src/main/resources/application.yml
- 인증 인가가 필요한 API 의 접근을 제한합니다
- 발급받은 Jwt를 헤더에 삽입하여 API 에 접근할 수 있습니다.
- JwtFilter 개발 및 시큐리티에 추가
- test api 를 만들어서 로직 작동 확인
- refresh 토큰을 이용한 accesstoken 갱신 로직 개발
- access token과 refresh token의 구분 로직 개발
=> [PH-35] Jwt 인증 인가 로직 개발

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/auth/service/ReIssueService.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/handler/LogoutSuccessHandler.java, src/main/java/org/myteam/server/global/security/jwt/JwtProvider.java, src/main/java/org/myteam/server/global/util/cookie/CookieUtil.java, src/main/java/org/myteam/server/global/util/date/DateFormatUtil.java, src/main/java/org/myteam/server/global/util/file/MediaUtils.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/domain/validator/MemberValidator.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java, src/main/java/org/myteam/server/oauth2/response/KakaoResponse.java, src/main/java/org/myteam/server/oauth2/response/NaverResponse.java, src/main/java/org/myteam/server/oauth2/unlink/controller/OAuth2UnlinkController.java
Feat/ph 84 회원가입 시 리프레시 토큰 관련 이슈 수정
Feat/ph 84 회원가입 시 리프레시 토큰 관련 이슈 수정
=> Feat/ph 84 회원가입 시 리프레시 토큰 관련 이슈 수정

build.gradle, src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/board/entity/Category.java, src/main/java/org/myteam/server/board/service/CategoryService.java, src/main/java/org/myteam/server/global/domain/Base.java, src/main/java/org/myteam/server/global/domain/BaseTime.java, src/main/java/org/myteam/server/global/domain/PlayHive.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
Feat/ph 84 회원가입 시 리프레시 토큰 관련 이슈 수정
Feat/ph 84 회원가입 시 리프레시 토큰 관련 이슈 수정
=> [error] 회원가입 시에도 발급되는 리프레시 쿠키를 사용할수 있도록 수정

src/main/java/org/myteam/server/common/certification/dto/CertificationCertifyRequest.java, src/main/java/org/myteam/server/common/certification/dto/CertificationEmailRequest.java
=> feat : 이메일 인증 관련 DTO 수정

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/auth/repository/RefreshJpaRepository.java, src/main/java/org/myteam/server/auth/service/ReIssueService.java, src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/handler/LogoutSuccessHandler.java, src/main/java/org/myteam/server/global/util/cookie/CookieUtil.java, src/main/java/org/myteam/server/global/util/domain/DomainUtil.java, src/main/java/org/myteam/server/member/dto/MemberStatusUpdateRequest.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java, src/main/java/org/myteam/server/oauth2/service/CustomOAuth2UserService.java
- OauthMember 테이블 삭제
- 소셜 로그인 성공 시 PENDING 상태로 멤버 테이블에 저장되도록 수정
- FRONT_URL, BACKEND_URL 환경 변수 추가
- OauthMember 테이블 삭제
- 소셜 로그인 성공 시 PENDING 상태로 멤버 테이블에 저장되도록 수정
- FRONT_URL, BACKEND_URL 환경 변수 추가
=> Feat/ph 108 fix : 소셜 로그인 부분 로직 수정 

src/main/java/org/myteam/server/util/slack/service/SlackService.java
* webhookurl을 생성자 주입으로 변경
* webhookurl을 생성자 주입으로 변경
* webhookurl을 생성자 주입으로 변경
* aws에 띄워지는지 확인
* 슬랙에 보내는 포맷 차후 수정
=> chore: slack webhook url 생성자 주입으로 변경

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/board/controller/reponse/BoardResponse.java, src/main/java/org/myteam/server/board/dto/BoardSaveRequest.java, src/main/java/org/myteam/server/board/entity/Board.java, src/main/java/org/myteam/server/board/entity/BoardCount.java, src/main/java/org/myteam/server/board/entity/Category.java, src/main/java/org/myteam/server/board/repository/BoardCountRepository.java, src/main/java/org/myteam/server/board/repository/BoardRepository.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/board/service/CategoryReadService.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/member/service/MemberReadService.java, src/main/java/org/myteam/server/util/ClientUtils.java
- 게시판(p_board) CRUD 기능 추가
- 게시글 생성, 수정, 상세 조회, 삭제 기능 추가하였습니다.
- 어드민이 수정/삭제 가능하게 작업했습니다.
- 게시판 검색 API, 게시글의 내용 작성 시 필요한 파일 업로드 API, 댓글 관련 API, 좋아요 관련 API 작업 예정입니다.
- API명세서 작성 예정입니다!
=> feat: 게시글 생성,수정,상세조회,삭제 기능 추가

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/util/ClientUtils.java
- 게시글 삭제 성공 시 메시지 수정
- 삭제 성공 시 메시지를 '카테고리 삭제 성공' -> '게시글 삭제 성공' 으로 수정하였습니다.
- 상기님이 리뷰주셨던 ClientUtils에서 .isEmpty()로 수정했습니다.
- 
-
=> chore: 게시글 삭제 성공 시 메시지 수정

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
fix : 리프레시 토큰 발급 시 쿠키에 베리어 문자열 제거 및 인코딩하던 로직 제거
리프레시 토큰 발급 시 쿠키에 베리어 문자열(Bearer) 추가 되었던 부분 제거함
- 
- 
- [O] 단위 테스트 확인(포스트맨 등..)
- [O] 통합 테스트 확인(서버 빌드되는지 확인)
=> fix : 리프레시 토큰 발급 시 쿠키에 베리어 문자열 제거 및 인코딩하던 로직 제거

docker-compose.yml
=> chore: 이미지 정책 변경

docker-compose.yml
- 
- 도커 컴포즈 kafka 힙 메모리 설정
- kafka의 JVM 힙 메모리 설정
- AWS 로그 보면서 에러 확인
=> fix: kafka 힙 메모리 설정

build.gradle, docker-compose.yml, src/main/java/org/myteam/server/chat/config/KafkaConfig.java, src/main/java/org/myteam/server/chat/config/WebSocketConfig.java, src/main/java/org/myteam/server/chat/controller/ChatController.java, src/main/java/org/myteam/server/chat/controller/FilterController.java, src/main/java/org/myteam/server/chat/dto/request/ChatMessage.java, src/main/java/org/myteam/server/chat/interceptor/StompHandler.java, src/main/java/org/myteam/server/chat/repository/ChatRoomRepository.java, src/main/java/org/myteam/server/chat/service/ChatWriteService.java, src/main/java/org/myteam/server/chat/service/KafkaConsumerService.java, src/main/java/org/myteam/server/chat/service/KafkaProducerService.java, src/main/java/org/myteam/server/chat/service/TopicManagementService.java
- 채팅 기능 구현
- EC2 kafka 힙 메모리 문제로 Spring stomp로의 변환
- Spring stomp 설정
-
=> feat: 채팅 로직 kafka -> spring stomp

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/inquiry/controller/InquiryController.java, src/main/java/org/myteam/server/inquiry/domain/Inquiry.java, src/main/java/org/myteam/server/inquiry/dto/request/InquiryRequest.java, src/main/java/org/myteam/server/inquiry/dto/response/InquiryResponse.java, src/main/java/org/myteam/server/inquiry/repository/InquiryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java, src/main/java/org/myteam/server/inquiry/service/InquiryWriteService.java, src/test/java/org/myteam/server/inquiry/service/InquiryReadServiceTest.java, src/test/java/org/myteam/server/inquiry/service/InquiryWriteServiceTest.java
- 문의하기 기능
- 문의하기 기능
- 내 문의하기 조회
- 
-
=> feat: 문의하기 기능 추가

src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/news/controller/NewsReplyController.java, src/main/java/org/myteam/server/news/domain/NewsReply.java, src/main/java/org/myteam/server/news/dto/controller/request/NewsReplyRequest.java, src/main/java/org/myteam/server/news/dto/controller/request/NewsReplySaveRequest.java, src/main/java/org/myteam/server/news/dto/controller/request/NewsReplyUpdateRequest.java, src/main/java/org/myteam/server/news/dto/repository/NewsReplyDto.java, src/main/java/org/myteam/server/news/dto/repository/NewsReplyMemberDto.java, src/main/java/org/myteam/server/news/dto/service/request/NewsReplySaveServiceRequest.java, src/main/java/org/myteam/server/news/dto/service/request/NewsReplyServiceRequest.java, src/main/java/org/myteam/server/news/dto/service/request/NewsReplyUpdateServiceRequest.java, src/main/java/org/myteam/server/news/dto/service/response/NewsReplyListResponse.java, src/main/java/org/myteam/server/news/dto/service/response/NewsReplyMemberResponse.java, src/main/java/org/myteam/server/news/dto/service/response/NewsReplyResponse.java, src/main/java/org/myteam/server/news/repository/NewsCommentQueryRepository.java, src/main/java/org/myteam/server/news/repository/NewsCommentRepository.java, src/main/java/org/myteam/server/news/repository/NewsReplyQueryRepository.java, src/main/java/org/myteam/server/news/repository/NewsReplyRepository.java, src/main/java/org/myteam/server/news/service/NewsReplyReadService.java, src/main/java/org/myteam/server/news/service/NewsReplyService.java, src/test/java/org/myteam/server/ControllerTestSupport.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/news/controller/NewsReplyControllerTest.java, src/test/java/org/myteam/server/news/service/NewsReplyReadServiceTest.java, src/test/java/org/myteam/server/news/service/NewsReplyServiceTest.java
- 뉴스 댓글에 대댓글 기능
- NewsReplyController
- NewsReplyService
- NewsReply Entity 생성
- 
- 마이페이지 댓글 리스트 작업
- 뉴스, 댓글, 대댓글 추천, 좋아요 작업
=> epic: 뉴스 대댓글기능

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/board/controller/reponse/BoardResponse.java, src/main/java/org/myteam/server/board/controller/reponse/CategoryResponse.java, src/main/java/org/myteam/server/board/domain/Board.java, src/main/java/org/myteam/server/board/domain/BoardCount.java, src/main/java/org/myteam/server/board/domain/BoardType.java, src/main/java/org/myteam/server/board/domain/Category.java, src/main/java/org/myteam/server/board/domain/CategoryType.java, src/main/java/org/myteam/server/board/dto/BoardSaveRequest.java, src/main/java/org/myteam/server/board/repository/BoardCountRepository.java, src/main/java/org/myteam/server/board/repository/BoardRepository.java, src/main/java/org/myteam/server/board/repository/CategoryJpaRepository.java, src/main/java/org/myteam/server/board/repository/CategoryRepository.java, src/main/java/org/myteam/server/board/repository/CategoryRepositoryImpl.java, src/main/java/org/myteam/server/board/repository/querydsl/CategoryQuerydslRepository.java, src/main/java/org/myteam/server/board/repository/querydsl/CategoryRepositoryCustom.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/board/service/CategoryReadService.java, src/main/java/org/myteam/server/board/service/CategoryService.java
- 게시글 crud 수정
- 회의를 통해 카테고리 ID를 쓰지 않고, boardType과 categoryType으로 받아 저장하는 방식으로 결정 되어 수정하였습니다.
- categoryType의 전적인증과, 플레이팁 enum은 boardType이 Esports인 경우에만 사용할 수 있습니다.
- enum 타입 다른 의견 있으시면 반영하겠습니다 :)
- 작성, 수정 시 category ID 대신 boardType, categoryType을 받도록 수정
- S3 업로드한 파일을 삭제하는 API 작성 예정입니다.
=> feat: 게시글 CRUD 코드 수정

src/main/java/org/myteam/server/global/page/request/PageInfoRequest.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/news/news/controller/NewsController.java, src/main/java/org/myteam/server/news/news/dto/controller/request/NewsRequest.java, src/main/java/org/myteam/server/news/news/dto/repository/NewsDto.java, src/main/java/org/myteam/server/news/news/dto/service/response/NewsResponse.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/main/java/org/myteam/server/news/newsComment/controller/NewsCommentController.java, src/main/java/org/myteam/server/news/newsComment/dto/controller/request/NewsCommentRequest.java, src/main/java/org/myteam/server/news/newsComment/dto/controller/request/NewsCommentSaveRequest.java, src/main/java/org/myteam/server/news/newsComment/dto/controller/request/NewsCommentUpdateRequest.java, src/main/java/org/myteam/server/news/newsComment/dto/repository/NewsCommentDto.java, src/main/java/org/myteam/server/news/newsComment/dto/repository/NewsCommentMemberDto.java, src/main/java/org/myteam/server/news/newsComment/dto/service/response/NewsCommentResponse.java, src/main/java/org/myteam/server/news/newsCount/controller/NewsCountController.java, src/main/java/org/myteam/server/news/newsCount/dto/service/response/NewsRecommendResponse.java, src/main/java/org/myteam/server/news/newsReply/controller/NewsReplyController.java, src/main/java/org/myteam/server/news/newsReply/dto/controller/request/NewsReplyRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/controller/request/NewsReplySaveRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/controller/request/NewsReplyUpdateRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/repository/NewsReplyDto.java, src/main/java/org/myteam/server/news/newsReply/dto/repository/NewsReplyMemberDto.java, src/main/java/org/myteam/server/news/newsReply/dto/service/response/NewsReplyMemberResponse.java, src/main/java/org/myteam/server/news/newsReply/dto/service/response/NewsReplyResponse.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/news/newsReply/controller/NewsReplyControllerTest.java
- 뉴스 API는 로그인을 안해도 사용 가능해야하므로 Security 제외
- Swagger API 설명
- SecurityConfig /api/news 추가
- Swagger API 설명 추가
- 
-
=> fix: 뉴스 api security설정, Swagger 설명추가

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/board/controller/BoardRecommendController.java, src/main/java/org/myteam/server/board/domain/Board.java, src/main/java/org/myteam/server/board/domain/BoardCount.java, src/main/java/org/myteam/server/board/domain/BoardRecommend.java, src/main/java/org/myteam/server/board/domain/BoardType.java, src/main/java/org/myteam/server/board/dto/reponse/BoardResponse.java, src/main/java/org/myteam/server/board/repository/BoardCountRepository.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/board/repository/BoardRecommendRepository.java, src/main/java/org/myteam/server/board/service/BoardCountReadService.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/board/service/BoardRecommendReadService.java, src/main/java/org/myteam/server/board/service/BoardRecommendService.java, src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java
- 게시글 추천하면 boardRecommend를 생성하고, boardCount의 recommendCount를 1 증가 시킵니다.
- 게시글 추천 삭제하면 boardRecommend를 삭제하고, boardCount의 recommendCount를 1 감소 시킵니다.
- 게시글 추천 API 추가.
- 게시글 추천 삭제 API 추가
- 게시글 조회 시 로그인한 사용자가 해당 게시글을 추천 했는지 여부를 isRecommended에 담아 내려주도록 응답값 추가
-
-
=> feat: 게시글 추천,추천삭제 API 추가 & 게시글 조회 시 로그인 사용자 추천 여부 응답값 추가

src/main/java/org/myteam/server/board/repository/BoardCommentRecommendRepository.java, src/main/java/org/myteam/server/board/repository/BoardCommentRepository.java, src/main/java/org/myteam/server/board/repository/BoardRecommendRepository.java, src/main/java/org/myteam/server/board/repository/BoardReplyRecommendRepository.java, src/main/java/org/myteam/server/board/repository/BoardReplyRepository.java, src/main/java/org/myteam/server/board/service/BoardCommentReadService.java, src/main/java/org/myteam/server/board/service/BoardCommentService.java, src/main/java/org/myteam/server/board/service/BoardReplyReadService.java, src/main/java/org/myteam/server/board/service/BoardReplyService.java, src/main/java/org/myteam/server/board/service/BoardService.java
- 
- 게시글 삭제 시 댓글,대댓글,추천 관련 데이터까지 삭제 되도록 로직 추가
- 게시글 댓글 삭제 시 대댓글, 추천 관련 데이터까지 삭제 되도록 로직 추가
- 게시글 대댓글 삭제 시 추천 관련 데이터까지 삭제 되도록 로직 추가
- 
-
=> feat: 게시글, 댓글, 대댓글 삭제시 하위 데이터들도 삭제되도록 수정

src/main/java/org/myteam/server/board/dto/reponse/BoardCommentSearchDto.java, src/main/java/org/myteam/server/board/dto/reponse/BoardDto.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/board/service/BoardCommentService.java, src/main/java/org/myteam/server/board/service/BoardReplyService.java, src/main/java/org/myteam/server/board/service/BoardService.java
- searchType이 COMMENT일 경우 search로 입력된 검색어로 댓글 검색 작업하였습니다.
댓글 데이터(댓글 ID -> 클릭시 댓글 상세 조회를 위한 ID, 댓글 내용) 응답값 추가하였습니다.
- 댓글 검색 필터 추가하였습니다.
- s3관련 이미지 삭제 시 이미지가 존재할경우에만 s3에 접근하여 삭제 하도록 if문 추가하였습니다.
- 
-
=> feat: 게시글 목록 조회 시 댓글 검색 추가

src/main/java/org/myteam/server/board/controller/BoardCommentController.java, src/main/java/org/myteam/server/board/repository/BoardCommentQueryRepository.java, src/main/java/org/myteam/server/board/service/BoardCommentReadService.java
- 
- 게시글 댓글 목록 검색시 BEST 3개 상단고정 (추천순, 같다면 최신순), 나머지 BEST 3개 제외한 댓글 목록 (최신순, 같다면 댓글 가나다순)
- 게시글 댓글 목록 검색은 orderType을 따로 받을 필요가 없어보여 제거하였습니다.
- 
-
=> feat: 게시판 댓글 목록 조회 수정

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/mypage/controller/MyPageController.java, src/main/java/org/myteam/server/mypage/dto/request/MyBoardSearchRequest.java, src/main/java/org/myteam/server/mypage/dto/request/MyBoardServiceRequest.java, src/main/java/org/myteam/server/mypage/service/MyPageReadService.java
- 
- 영웅님께서 요청 주신 boardSearchRequest Dto와 내가쓴게시글 조회 dto 분리하였습니다
- MyPageController와 같은 API라서 BoardController에서 테스트용으로 쓰던 내가 쓴 게시글 목록 조회 제거하였습니다.
-
=> chore: 내가 쓴 게시글 목록 조회 RequestDto 새로 생성 후 변경

src/main/java/org/myteam/server/match/match/domain/Match.java, src/main/java/org/myteam/server/match/match/dto/service/response/MatchResponse.java, src/main/java/org/myteam/server/match/match/repository/MatchQueryRepository.java, src/main/java/org/myteam/server/match/match/service/MatchReadService.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- 경기 일주일치만 가져오도록 수정
- 경기일정 응답에 장소도 추가
- 
- 
- memberid로 댓글 목록 조회 메소드 개발
=> feat: 경기일정 날짜 조건 추가

src/main/java/org/myteam/server/board/dto/reponse/BoardCommentResponse.java, src/main/java/org/myteam/server/board/dto/reponse/BoardDto.java, src/main/java/org/myteam/server/board/dto/reponse/BoardReplyResponse.java, src/main/java/org/myteam/server/board/dto/reponse/BoardResponse.java, src/main/java/org/myteam/server/util/ClientUtils.java
- 
- 개발자 모드에서 response통해 IP 노출 안되도록 서버에서 IP 뒷부분 마스크 처리 하였습니다.
- 
-
=> chore: 게시판 응답시 IP 뒷부분 마스크 처리

src/main/java/org/myteam/server/game/controller/GameController.java, src/main/java/org/myteam/server/game/domain/GameDiscount.java, src/main/java/org/myteam/server/game/domain/GameEvent.java, src/main/java/org/myteam/server/game/dto/response/GameDiscountDto.java, src/main/java/org/myteam/server/game/dto/response/GameDiscountListResponse.java, src/main/java/org/myteam/server/game/dto/response/GameEventDto.java, src/main/java/org/myteam/server/game/dto/response/GameEventListResponse.java, src/main/java/org/myteam/server/game/repository/GameQueryRepository.java, src/main/java/org/myteam/server/game/service/GameReadService.java, src/main/java/org/myteam/server/global/page/request/PageInfoRequest.java, src/main/java/org/myteam/server/global/page/request/PageInfoServiceRequest.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
- 크롤링되어 저장된 진행중인 게임 이벤트와 게임 할인정보를 조회하는 API 입니다.
- 기획 확인 된 내용인 각각 최대 10개씩 조회(5개씩 2페이지) 될 수있도록 노출 날짜가 오늘인 것중 최대 10개 조회하여 조회합니다.
- 따로 검색필터 없이 페이징만 적용해서 page 관련 request부분도 page와 size만 받을 수 있도록 toServiceRequest추가하였습니다!
- 진행중인 게임 이벤트 목록 조회 API
- 게임 할인 목록 조회 API
- 
-
=> feat: 게임 이벤트, 할인 정보 조회 API 추가

src/main/java/org/myteam/server/board/dto/reponse/BoardListResponse.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/notice/Repository/NoticeQueryRepository.java, src/main/java/org/myteam/server/notice/dto/response/NoticeResponse.java
- 
- 게시글 목록 조회시 최신 공지글 최대 2개 고정 노출되도록 추가 하였습니다.
공지사항 최대 2개 고정 추가해야할 경우, noticeQueryRepository에 만들어두었으니 사용하시면 됩니다!
`List<NoticeDto> noticeList = noticeQueryRepository.getFixNotice();`
- NoticeDto에서 createdIP 응답으로는 안내려줘도 되어서 제거하였습니다!
-
=> feat: 게시글 목록 조회시 최신 공지글 2개 고정 노출 추가

src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java
- 목록 조회시에 정렬 기준이 같을경우 N차 정렬에 대한 기획 확정을 받아 반영하였습니다 !
```
- 인기순
- 추천수 내림차순 > 조회수 + 댓글수 내림차순 > 제목 오름차순
- 최신순
- 날짜순 내림차순 > 제목 오름차순
- 댓글순
- 댓글수 내림차순 > 제목 오름차순
```
이렇게 확정 지어주셨는데 저는 제목 오름차순 뒤에 id값 내림차순까지 추가하였습니다!
- 게시글 목록 조회 시 정렬 구체화
- 
-
=> chore: 게시글 목록 조회시 정렬 구체화 기획 반영

src/main/java/org/myteam/server/news/news/controller/NewsController.java, src/main/java/org/myteam/server/news/news/service/NewsReadService.java
- 의존성 순환 문제로 인한 Controller에서 조회수 증가시키도록
- 
- 
-
=> fix: 뉴스조회수 증가 controller단으로 옮김

src/main/java/org/myteam/server/news/news/dto/repository/NewsDto.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/test/java/org/myteam/server/news/news/service/NewsReadServiceTest.java
- 뉴스 리스트 조회시 댓글 수도 내려주도록 추가했습니다.
- NewsQueryRepository commentCount 추가
- 
-
=> feat: 뉴스 리스트 조회시 댓글 수도 내려주도록 추가

src/main/java/org/myteam/server/news/newsComment/repository/NewsCommentQueryRepository.java
- jwt토큰을 안받았을시 사용자가 null이면 에러가 발생해 오류 수정하엿습니다
- 
- 
-
=> fix: member가 null이면 false로 반환되도록

src/main/java/org/myteam/server/board/repository/BoardCommentQueryRepository.java, src/main/java/org/myteam/server/board/service/BoardCommentReadService.java, src/main/java/org/myteam/server/board/service/BoardReplyReadService.java, src/main/java/org/myteam/server/improvement/repository/ImprovementCommentQueryRepository.java, src/main/java/org/myteam/server/improvement/service/ImprovementCommentReadService.java, src/main/java/org/myteam/server/improvement/service/ImprovementReplyReadService.java, src/main/java/org/myteam/server/inquiry/repository/InquiryCommentQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryCommentReadService.java, src/main/java/org/myteam/server/inquiry/service/InquiryReplyReadService.java, src/main/java/org/myteam/server/mypage/controller/MyPageController.java, src/main/java/org/myteam/server/mypage/service/MyPageReadService.java, src/main/java/org/myteam/server/mypage/service/MyPageService.java, src/main/java/org/myteam/server/news/newsComment/repository/NewsCommentQueryRepository.java, src/main/java/org/myteam/server/news/newsComment/service/NewsCommentReadService.java, src/main/java/org/myteam/server/news/newsReply/repository/NewsReplyQueryRepository.java, src/main/java/org/myteam/server/news/newsReply/service/NewsReplyReadService.java, src/main/java/org/myteam/server/notice/Repository/NoticeCommentQueryRepository.java, src/main/java/org/myteam/server/notice/service/NoticeCommentReadService.java, src/main/java/org/myteam/server/notice/service/NoticeReplyReadService.java
- 마이페이지 내 댓글 추가
- 마이페이지 내 댓글 카운트를 구현하였습니다.
- 
-
=> feat: 마이페이지 댓글 count 추가

src/main/java/org/myteam/server/global/config/RedisConfig.java
- 레디스 캐시 디테일한 설정
- 레디스 캐시 설정 5분으로 하였습니다.
- `@Cacheable`을 통해서 캐싱할 수 있습니다.
- 
-
=> fix: redis 캐시 설정

src/main/java/org/myteam/server/news/newsComment/domain/NewsComment.java, src/main/java/org/myteam/server/news/newsReply/domain/NewsReply.java, src/test/java/org/myteam/server/news/newsComment/service/NewsCommentServiceTest.java
-  뉴스댓글 삭제시 하위 참조 테이블 데이터도 함께 삭제되도록 추가
- 
- 
-
=> fix: 뉴스댓글 삭제시 하위 참조 테이블 데이터도 함께 삭제되도록 추가

src/main/java/org/myteam/server/board/dto/reponse/BoardResponse.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/improvement/dto/response/ImprovementResponse.java, src/main/java/org/myteam/server/improvement/repository/ImprovementQueryRepository.java, src/main/java/org/myteam/server/improvement/service/ImprovementReadService.java, src/main/java/org/myteam/server/improvement/service/ImprovementService.java, src/main/java/org/myteam/server/inquiry/dto/response/InquiryResponse.java, src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java, src/main/java/org/myteam/server/news/news/dto/service/response/NewsResponse.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/main/java/org/myteam/server/news/news/service/NewsReadService.java, src/main/java/org/myteam/server/notice/dto/response/NoticeResponse.java, src/main/java/org/myteam/server/notice/repository/NoticeQueryRepository.java, src/main/java/org/myteam/server/notice/service/NoticeReadService.java, src/main/java/org/myteam/server/notice/service/NoticeService.java
- 상세 조회시 ID값을 가지고 이전글 다음글을 조회하였습니다. 
- 게시판은 상세 조회한 게시판 타입/카테고리 타입을 기준으로 이전글 다음글을 불러오게했고, 뉴스도 타입을 기준으로 불러왔습니다.
나머지는 분류 타입이 없어 해당 ID를 기준으로 불러왔습니다.
- 게시판, 개선요청, 문의, 뉴스, 공지사항 상세조회 시 이전글, 다음글 ID 추가하였습니다.
- 
-
=> chore: 게시판, 개선요청, 문의, 뉴스, 공지사항 상세조회 시 이전글, 다음글 ID 추가

src/main/java/org/myteam/server/match/match/dto/service/response/MatchResponse.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- 경기일정에 시간 추가
- MatchController 응답값 객체에 startTime추가
- 
-
=> fix: 경기일정에 시간 추가

src/main/java/org/myteam/server/match/match/domain/Match.java, src/main/java/org/myteam/server/match/match/dto/service/response/MatchResponse.java, src/main/java/org/myteam/server/match/match/repository/MatchQueryRepository.java, src/test/java/org/myteam/server/IntegrationTestSupport.java
- 리그명추가, 종료시간 기준으로 경기일정 필터링 추가했습니다.
- 일정 푸시로 인해 머지하겠습니다ㅠ 큰 작업도 아니였습니다
- 
- 
-
=> feat: 경기일정 리그명추가, 종료시간 기준으로 조건 수정

src/main/java/org/myteam/server/news/news/dto/controller/request/NewsRequest.java, src/main/java/org/myteam/server/news/news/dto/service/request/NewsServiceRequest.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/test/java/org/myteam/server/news/news/controller/NewsControllerTest.java, src/test/java/org/myteam/server/news/news/service/NewsReadServiceTest.java
- 계시판 검색과 같은 포맷으로 뉴스리스트 조회하도록 수정했습니다.
- 
- 
-
=> feat: 뉴스 댓글, 내용검색 추가

src/main/java/org/myteam/server/comment/util/CommentFactory.java, src/main/java/org/myteam/server/news/news/dto/repository/NewsCommentSearchDto.java, src/main/java/org/myteam/server/news/news/dto/repository/NewsDto.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/news/news/service/NewsReadServiceTest.java
- 계시판과 동일하게 댓글 조회시 댓글도 함께 내려주도록 하였습니다.
- 계시판과 코드 동일하여 바로 머지하게습니다
- 
- 
-
=> feat: 뉴스 댓글 검색 시 댓글 함께 내려주도록 수정

build.gradle, docker-compose.yml, src/main/java/org/myteam/server/ServerApplication.java, src/main/java/org/myteam/server/global/config/FeignConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/util/redis/RedisService.java, src/main/java/org/myteam/server/match/match/client/GoogleFeignClient.java, src/main/java/org/myteam/server/match/match/controller/MatchController.java, src/main/java/org/myteam/server/match/match/dto/client/reponse/GoogleYoutubeResponse.java, src/main/java/org/myteam/server/match/match/dto/client/request/GoogleYoutubeRequest.java, src/main/java/org/myteam/server/match/match/dto/service/response/MatchEsportsYoutubeResponse.java, src/main/java/org/myteam/server/match/match/repository/MatchRepository.java, src/main/java/org/myteam/server/match/match/service/MatchReadService.java, src/main/java/org/myteam/server/match/match/service/MatchYoutubeService.java, src/main/resources/application-dev.yml, src/main/resources/application-test.yml, src/test/java/org/myteam/server/match/match/controller/MatchControllerTest.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- 길표님과 의논 후 당일 제일 최근 경기시작시간 한시간전부터 유튜브 API 조회하도록 했습니다.
- 조회하여 동영상 ID가 내려온경우 Redis에 저장해두고 조회하도록 했습니다. (당일 API 제한 수가 있어 API 호출 최소화 하기위해 사용하였습니다)
- Redis에 url이 없을 시 -> 유튜브 API 조회하여 Redis에 세팅 (5시간 만료기간 설정)
- Redis에 url이 있을시 -> 그래서 응답
- 
- 
-
=> feat: 경기시간 한시간전에 조회시 유튜브 실시간 API 조회하도록

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/news/news/dto/repository/NewsDto.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/test/java/org/myteam/server/news/news/service/NewsReadServiceTest.java
- 계시판과 동일하게 hot 뉴스여부 추가했습니다.
- 뉴스 통합검색 버그 발생하여 수정했습니다.
- 
- 
-
=> feat: 뉴스목록조회시 hot 뉴스 표시추가

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/match/match/controller/MatchController.java, src/main/java/org/myteam/server/match/match/dto/service/response/MatchEsportsScheduleResponse.java, src/main/java/org/myteam/server/match/match/repository/MatchQueryRepository.java, src/main/java/org/myteam/server/match/match/service/MatchReadService.java, src/main/java/org/myteam/server/news/news/controller/NewsController.java, src/main/java/org/myteam/server/news/news/dto/repository/NewsCommentSearchDto.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/match/match/controller/MatchControllerTest.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- ESPORTS 경기일정 조회 API를 따로 만들어 프론트에서 따로 조회해서 조합하기로 결정했습니다.
- ESPORTS 경기일정 날짜별로 그룹핑하도록 수정
- 
-
=> feat: esports 경기일정 분리

src/main/java/org/myteam/server/match/match/dto/client/reponse/GoogleYoutubeResponse.java
- 유튜브API 조회시 응답객체에 기본생성자 추가
- 
- 
-
=> fix: 기본생성자가 있어야 데이터가 들어감

src/main/java/org/myteam/server/match/util/PercentageUtil.java, src/test/java/org/myteam/server/match/matchPrediction/dto/MatchPredictionResponseTest.java
- 경기예측이 아직 진행되지 않아 0, 0일때 그대로 0, 0으로 내려주도록 버그 수정했습니다.
- 
- 
-
=> fix: 경기예측 퍼센트 수정

src/main/java/org/myteam/server/global/util/redis/RedisService.java, src/main/java/org/myteam/server/match/match/dto/service/response/MatchEsportsYoutubeResponse.java, src/main/java/org/myteam/server/match/match/service/MatchReadService.java, src/main/java/org/myteam/server/match/match/service/MatchYoutubeService.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- 길표님 요청으로 유튜브 url이 아닌 videoId만 내려주도록 수정하였습니다.
- 
- 
-
=> fix: 실시간 유튜브 url   video id만

src/main/java/org/myteam/server/news/news/dto/controller/request/NewsRequest.java, src/main/java/org/myteam/server/news/news/dto/service/request/NewsServiceRequest.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java
- 제동님요청으로 메인화면에서는 뉴스 페이징이 3-7, 8-12 이런식으로 앞에 3개를 잘라야해서 startIndex 추가하여 원하는 곳부터 데이터 가져올수있도록 수정하였습니다.
- 
- 
-
=> feat: 메인화면에서 유연하게 사용가능하도록 startIndex 추가

src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/match/matchPrediction/controller/MatchPredictionController.java, src/main/java/org/myteam/server/match/matchPrediction/dto/service/response/MatchPredictionResponse.java, src/main/java/org/myteam/server/match/matchPrediction/service/MatchPredictionReadService.java, src/main/java/org/myteam/server/match/matchPrediction/service/MatchPredictionService.java, src/main/java/org/myteam/server/match/matchPredictionMember/domain/MatchPredictionMember.java, src/main/java/org/myteam/server/match/matchPredictionMember/dto/service/response/MatchPredictionMemberDeleteResponse.java, src/main/java/org/myteam/server/match/matchPredictionMember/dto/service/response/MatchPredictionMemberResponse.java, src/main/java/org/myteam/server/match/matchPredictionMember/repository/MatchPredictionMemberRepository.java, src/main/java/org/myteam/server/match/matchPredictionMember/service/MatchPredictionMemberReadService.java, src/main/java/org/myteam/server/match/matchPredictionMember/service/MatchPredictionMemberService.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/match/matchPrediction/service/MatchPredictionReadServiceTest.java, src/test/java/org/myteam/server/match/matchPrediction/service/MatchPredictionServiceTest.java, src/test/java/org/myteam/server/match/matchPredictionMember/service/MatchPredictionMemberReadServiceTest.java, src/test/java/org/myteam/server/match/matchPredictionMember/service/MatchPredictionMemberServiceTest.java
- 경기예측시 사용자가 어디에 경기예측을 걸었는지 저장하도록 추가
- 경기예측 조회시 로그인한 사용자가 투표했는지 여부도 내려주도록 추가
- 
- 
-
=> fix: 경기예측 사용자 저장

src/main/java/org/myteam/server/auth/service/TokenService.java, src/main/java/org/myteam/server/global/security/jwt/JwtProvider.java
- 재발급시 만료된 accesstoken도 사용자정보 가져올수있는 메소드 추가
- 
- 
-
=> fix: 만료된 accesstoken도 사용자정보 가져올수있는 메소드 추가

src/main/java/org/myteam/server/aop/CommonCountAspect.java, src/main/java/org/myteam/server/news/news/controller/NewsController.java
- 
- 프론트측에서 메타 데이터 때문에 상세 요청 API를 2번 호출하게 되면서 생기는 카운트 증가 문제를 해결했습니다.
- API 요청 시 요청 파라미터에 'openGraph'를 'true'로 요청하면 AOP에서 봇과 oepnGraph이 'true'인 경우는 카운트 증가를 하지 않습니다!
- 
-
=> fix: 상세 조회 API 호출인 경우 openGraph true로 청하면 카운트 안되도록 수정

src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
- cors 추가
- SecurityConfig의 결합도를 낮추고 cors 필터 추가하였습니다.
- WebConfig.class 작업
- SecurityConfig.class 수정
-
=> fix: cors 추가 및 수정
