MT-TEAM-Org/server

build.gradle, src/main/java/org/myteam/server/ServerApplication.java, src/main/java/org/myteam/server/auth/controller/AuthController.java, src/main/java/org/myteam/server/auth/dto/LoginRequestDto.java, src/main/java/org/myteam/server/auth/dto/SignupRequestDto.java, src/main/java/org/myteam/server/auth/dto/TokenResponseDto.java, src/main/java/org/myteam/server/auth/service/AuthService.java, src/main/java/org/myteam/server/global/config/PasswordEncoderConfig.java, src/main/java/org/myteam/server/global/jwt/JwtProperties.java, src/main/java/org/myteam/server/global/jwt/JwtProvider.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/repository/MemberRepository.java, src/main/resources/application-auth.yml, src/main/resources/application-dev.yml, src/main/resources/application.properties, src/main/resources/application.yml
- ID 와 PW 를 이용한 회원가입 및 로그인 기능
- 회원가입과 로그인 시 Jwt가 발급됩니다.
- 테스트를 위한 h2-db 의존성 추가
- 시큐리티 설정 비활성화
- 로그인 및 회원 가입 로직 개발
- application.yml 을 profile 에 맞춰서 반영하도록 수정
- Jwt인증, 인가 Filter 개발
- 전역 예외 핸들러 개발
=> [CM-46] 기본 로그인, 회원가입 로직개발

src/main/java/org/myteam/server/global/web/response/ResponseStatus.java
API 응답(ResponseDto) Status Enum Commit
API 응답(ResponseDto) Status Enum Commit
=> API 응답(ResponseDto) Status Enum Commit

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/oauth2/handler/OAuth2LoginFailureHandler.java
소셜 로그인 실패시 핸들러 파일 추가
소셜 로그인 실패시 핸들러 파일 추가
=> 소셜 로그인 실패시 핸들러 파일 추가

src/main/java/org/myteam/server/global/security/dto/CustomUserDetails.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/handler/LogoutSuccessHandler.java, src/main/java/org/myteam/server/global/security/service/CustomUserDetailsService.java, src/main/java/org/myteam/server/global/security/util/PasswordUtil.java, src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/domain/MemberStatus.java, src/main/java/org/myteam/server/member/dto/MemberDeleteRequest.java, src/main/java/org/myteam/server/member/dto/MemberResponse.java, src/main/java/org/myteam/server/member/dto/MemberSaveRequest.java, src/main/java/org/myteam/server/member/dto/MemberUpdateRequest.java, src/main/java/org/myteam/server/member/dto/PasswordChangeRequest.java, src/main/java/org/myteam/server/member/service/MemberService.java
유저 기존 로직 파악 및 코드 변경 (누락 코드 커밋)
유저 기존 로직 파악 및 코드 변경 (누락 코드 커밋)
1. TODO_ 라고 되어진 부분 작업
2. 이메일 연동 작업
3. 이메일 연동에 따른 회원 가입 프로세스 보완
4. 로그아웃 부분 처리
5. 리프레시 토큰 처리
=> 유저 기존 로직 파악 및 코드 변경 (누락 코드 커밋)

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/auth/domain/Tokens.java, src/main/java/org/myteam/server/auth/entity/Refresh.java, src/main/java/org/myteam/server/auth/repository/RefreshJpaRepository.java, src/main/java/org/myteam/server/auth/service/ReIssueService.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/global/exception/PlayHiveException.java, src/main/java/org/myteam/server/global/exception/PlayHiveExceptionController.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/filter/AuthenticationEntryPointHandler.java, src/main/java/org/myteam/server/global/security/filter/CustomAccessDeniedHandler.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/handler/LogoutSuccessHandler.java, src/main/java/org/myteam/server/global/security/jwt/JwtProvider.java, src/main/java/org/myteam/server/member/controller/AdminController.java, src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/controller/response/MemberResponse.java, src/main/java/org/myteam/server/member/dto/ExistMemberRequest.java, src/main/java/org/myteam/server/member/dto/MemberDeleteRequest.java, src/main/java/org/myteam/server/member/dto/MemberGetRequest.java, src/main/java/org/myteam/server/member/dto/MemberStatusUpdateRequest.java, src/main/java/org/myteam/server/member/dto/MemberUpdateRequest.java, src/main/java/org/myteam/server/member/repository/MemberJpaRepository.java, src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java, src/main/java/org/myteam/server/util/CookieUtil.java
Ph 93  유저 도메인 API 작업
Ph 93  유저 도메인 API 작업
https://onedreamdesign.atlassian.net/wiki/spaces/~5f4c7fe891e67a003f21bfa7/database/10059783?atl_f=PAGETREE
=> Ph 93  유저 도메인 완성

src/main/java/org/myteam/server/member/controller/AdminController.java, src/main/java/org/myteam/server/member/repository/MemberJpaRepository.java, src/main/java/org/myteam/server/member/repository/MemberRepository.java, src/main/java/org/myteam/server/member/repository/MemberRepositoryImpl.java, src/main/java/org/myteam/server/member/service/MemberService.java
MemberRepository 추가
MemberService 모두 MemberResponse 만 반환하도록 처리
MemberRepository 추가
MemberService 모두 MemberResponse 만 반환하도록 처리
=> MemberRepository 추가, MemberService 모두 MemberResponse 만 반환하도록 처리

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/common/certification/controller/CertificationController.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/global/exception/ErrorResponse.java, src/main/java/org/myteam/server/global/exception/PlayHiveException.java, src/main/java/org/myteam/server/global/exception/PlayHiveExceptionController.java, src/main/java/org/myteam/server/global/exception/aop/CustomValidationAdvice.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/handler/LogoutSuccessHandler.java, src/main/java/org/myteam/server/member/controller/AdminController.java, src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
validation AOP 추가 및 로그아웃 경로에 대한 cookie path 추가
validation AOP 추가 및 로그아웃 경로에 대한 cookie path 추가
=> Ph 93  validation AOP 추가 및 로그아웃 경로에 대한 cookie path 추가

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/auth/service/ReIssueService.java, src/main/java/org/myteam/server/global/domain/PlayHive.java, src/main/java/org/myteam/server/global/domain/PlayHiveValidator.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/member/controller/AdminController.java, src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/controller/response/MemberResponse.java, src/main/java/org/myteam/server/member/dto/MemberRoleUpdateRequest.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/service/MemberService.java
권한 변경 API 및 테스트용 Token 발급 API 추가
=> 권한 변경 API, 테스트 토큰 발급 API 추가

src/main/java/org/myteam/server/auth/service/ReIssueService.java, src/main/java/org/myteam/server/global/security/dto/CustomUserDetails.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/jwt/JwtProvider.java, src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/oauth2/dto/CustomOAuth2User.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java, src/main/java/org/myteam/server/oauth2/service/CustomOAuth2UserService.java
유저의 상태가 ACTIVE 가 아닌 경우 토큰 발급 되지 않도록 처리
유저의 상태가 ACTIVE 가 아닌 경우 토큰 발급 되지 않도록 처리
=> 유저의 상태가 ACTIVE 가 아닌 경우 토큰 발급 되지 않도록 처리

src/main/java/org/myteam/server/member/controller/MemberController.java
=> 관리자 토큰 발급 메서드 삭제

src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
PENDING 상태인 경우 리프레시 토큰만 발급하도록 하는 코드 재수정
=> PENDING 상태인 경우 리프레시 토큰만 발급하도록 하는 코드 재수정

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
[refactor] Security Config 파일 내용 수정
[refactor] Security Config 파일 내용 수정
[refactor] Security Config 파일 내용 수정
[refactor] Security Config 파일 내용 수정
=> [refactor] Security Config 파일 내용 수정

src/main/java/org/myteam/server/global/config/WebConfig.java
cors 설정 추가 - Authorization 보이지 않는 부분 수정
cors 설정 추가 - Authorization 보이지 않는 부분 수정
=> cors 설정 추가 - Authorization 보이지 않는 부분 수정

src/main/java/org/myteam/server/member/service/MemberService.java
feat : 로컬 회원 가입시 상태 ACTIVE 로 지정 되도록 변경
feat : 로컬 회원 가입시 상태 ACTIVE 로 지정 되도록 변경
=> feat : 로컬 회원 가입시 상태 ACTIVE 로 지정 되도록 변경

src/main/java/org/myteam/server/member/dto/MemberUpdateRequest.java
refactor : MemberUpdateRequest status 항목 제거
=> refactor : MemberUpdateRequest status 항목 제거

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/member/entity/Oauth2Member.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> Feat/ph 108 이메일 인증관련 URL 오픈

src/main/java/org/myteam/server/common/certification/controller/CertificationController.java, src/main/java/org/myteam/server/common/certification/dto/CertificationCertifyRequest.java
=> feat : 이메일 인증 관련 DTO 수정

src/main/resources/application-dev.yml
=> feat : 이메일 인증 관련 로그 확인용 커밋

src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
=> feat : cors 전체 경로 허용으로 변경

src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
=> feat : cors 변경 내용 원복

src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
=> feat : cors 도메인 추가

src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> test : api 테스트를 위한 커밋

src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
revert : "api 테스트를 위한 커밋" 원복
revert : "api 테스트를 위한 커밋" 원복
=> revert : "api 테스트를 위한 커밋" 원복

docker-compose.yml
- front_url 추가
env-add : docker-compose.yml 파일 수정
env-add : docker-compose.yml 파일 수정
=> env-add : docker-compose.yml 파일 수정

src/main/java/org/myteam/server/global/config/WebConfig.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
fix : localhost 도메인 cors 추가
fix : localhost 도메인 cors 추가
=> fix : localhost 도메인 cors 추가

src/main/java/org/myteam/server/auth/controller/TestController.java, src/main/java/org/myteam/server/auth/dto/AuthRequest.java, src/main/java/org/myteam/server/auth/dto/AuthResponse.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/filter/TokenAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/jwt/JwtProvider.java, src/main/java/org/myteam/server/global/security/service/CustomUserDetailsService.java, src/main/java/org/myteam/server/member/controller/MemberController.java
fix : 토큰만료, 잘못된 토큰 입력 시에 대한 에러 응답 형식 변경 및 테스트 로그인 API 개발
fix : 토큰만료, 잘못된 토큰 입력 시에 대한 에러 응답 형식 변경 및 테스트 로그인 API 개발
=> fix : 토큰만료, 잘못된 토큰 입력 시에 대한 에러 응답 형식 변경 및 테스트 로그인 API 개발

src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/dto/ExistMemberNicknameRequest.java
- /exists/email API 삭제
- MemberController 의 getMemberType 함수 URL 변경: /type/{email} -> /{email}/type 로 URL 변경
fix : 기존 API 코드 리팩터링
=> fix : 기존 API 코드 리팩터링

src/main/java/org/myteam/server/test/controller/GlobalTestController.java
=> 슬랙 연동 테스트입니다.

src/main/java/org/myteam/server/test/controller/GlobalTestController.java
=> chore: 슬랙 테스트를 위한 코드 수정

src/main/java/org/myteam/server/test/controller/GlobalTestController.java
=> chore: 슬랙 연동 테스트

docker-compose.yml
- 
- docker-compose 오타 수정
- 
-
=> fix: docker-compose 오타 수정

src/main/java/org/myteam/server/upload/service/S3PresignedUrlService.java
- 
- equalsIgnoreCase 보다 equals가 맞다고 생각하여 수정하였습니다
- 
-
=> chore: 서비스 코드 equals로 수정

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
- 쿠키가 공유되지 않아 테스트 코드로 변경
- 쿠키가 공유되지 않아 테스트 코드로 변경
- 
-
=> test : 쿠키가 공유되지 않아 테스트 코드로 변경

src/main/java/org/myteam/server/auth/service/ReIssueService.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
- test : 쿠키가 공유되지 않아 테스트 코드 원복 및 쿠키 공유 되지 않던 원인 코드 수정
- test : 쿠키가 공유되지 않아 테스트 코드 원복 및 쿠키 공유 되지 않던 원인 코드 수정
- 
-
=> test : 쿠키가 공유되지 않아 테스트 코드 원복 및 쿠키 공유 되지 않던 원인 코드 수정

src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
- fix : 소셜 로그인 리다이렉트 시 정상 로그인 되었음에도 토큰 발급되지 않는 이슈 수정
- fix : 소셜 로그인 리다이렉트 시 정상 로그인 되었음에도 토큰 발급되지 않는 이슈 수정
- 
-
=> fix : 소셜 로그인 리다이렉트 시 정상 로그인 되었음에도 토큰 발급되지 않는 이슈 수정

docker-compose.yml, src/main/java/org/myteam/server/upload/config/S3ConfigLocal.java, src/main/resources/application-dev.yml
=> fix: minio 연결 에러 수정

src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java, src/main/java/org/myteam/server/oauth2/response/KakaoResponse.java
=> fix: 소셜로그인 대응

src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/global/util/cookie/CookieUtil.java
=> fix: cookie 설정 변경

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/util/cookie/CookieUtil.java
=> fix: 코드 원복

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/news/news/dto/controller/request/NewsRequest.java, src/main/java/org/myteam/server/news/newsComment/dto/controller/request/NewsCommentRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/controller/request/NewsReplyRequest.java, src/test/java/org/myteam/server/news/news/controller/NewsControllerTest.java, src/test/java/org/myteam/server/news/newsComment/controller/NewsCommentControllerTest.java, src/test/java/org/myteam/server/news/newsReply/controller/NewsReplyControllerTest.java
- Controller 테스트를 modelAttritube에 맞게 수정이 안되어있어서 수정했습니다ㅠ
- 
- 
-
=> fix: 뉴스 Controller 테스트코드 수정

src/main/java/org/myteam/server/news/newsComment/dto/repository/NewsCommentMemberDto.java, src/main/java/org/myteam/server/news/newsCount/service/NewsCountService.java, src/main/java/org/myteam/server/news/newsCountMember/dto/service/response/NewsCountMemberDeleteResponse.java, src/main/java/org/myteam/server/news/newsCountMember/dto/service/response/NewsCountMemberResponse.java, src/main/java/org/myteam/server/news/newsCountMember/repository/NewsCountMemberRepository.java, src/main/java/org/myteam/server/news/newsCountMember/service/NewsCountMemberReadService.java, src/main/java/org/myteam/server/news/newsCountMember/service/NewsCountMemberService.java, src/main/java/org/myteam/server/news/newsReply/dto/repository/NewsReplyDto.java, src/main/java/org/myteam/server/news/newsReply/dto/repository/NewsReplyMemberDto.java, src/test/java/org/myteam/server/news/newsComment/service/NewsCommentReadServiceTest.java, src/test/java/org/myteam/server/news/newsComment/service/NewsCommentServiceTest.java, src/test/java/org/myteam/server/news/newsCount/service/NewsCountServiceTest.java, src/test/java/org/myteam/server/news/newsCountMember/NewsCountMemberReadServiceTest.java, src/test/java/org/myteam/server/news/newsCountMember/NewsCountMemberServiceTest.java, src/test/java/org/myteam/server/news/newsReply/service/NewsReplyReadServiceTest.java, src/test/java/org/myteam/server/news/newsReply/service/NewsReplyServiceTest.java
- 영웅님이 작업해주신 member publicid로 변경 관련해서 뉴스쪽 모두 변경했습니다 바로 머지하겠습니다!
- 
- 
-
=> fix: member publicId 모두 변경

src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/entity/MemberActivity.java, src/main/java/org/myteam/server/member/service/MemberService.java
=> fix: 로그인 로직 에러 수정

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/news/news/domain/News.java, src/main/java/org/myteam/server/news/news/dto/repository/NewsDto.java, src/main/java/org/myteam/server/news/news/dto/service/response/NewsResponse.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/main/resources/application-dev.yml, src/test/java/org/myteam/server/IntegrationTestSupport.java
- 뉴스쪽 컬럼명이 어색해서 변경했습니다
- 
- 
-
=> fix: 컬럼 postDate로 변경

src/main/java/org/myteam/server/auth/controller/AuthTestController.java, src/main/java/org/myteam/server/member/controller/AdminController.java, src/main/java/org/myteam/server/member/controller/MemberController.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/dto/MemberUpdateRequest.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/entity/MemberActivity.java, src/main/java/org/myteam/server/member/service/MemberReadService.java, src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/member/service/MemberWriteService.java, src/main/java/org/myteam/server/member/service/SecurityReadService.java, src/main/java/org/myteam/server/news/dto/repository/NewsCommentMemberDto.java, src/main/java/org/myteam/server/news/dto/repository/NewsReplyMemberDto.java, src/main/java/org/myteam/server/news/dto/service/response/NewsCommentMemberResponse.java, src/main/java/org/myteam/server/news/dto/service/response/NewsReplyMemberResponse.java, src/main/java/org/myteam/server/profile/controller/MemberProfileController.java, src/main/java/org/myteam/server/profile/dto/request/ProfileRequestDto.java, src/main/java/org/myteam/server/profile/dto/response/ProfileResponseDto.java, src/test/java/org/myteam/server/ControllerTestSupport.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/inquiry/service/InquiryReadServiceTest.java, src/test/java/org/myteam/server/inquiry/service/InquiryWriteServiceTest.java, src/test/java/org/myteam/server/member/service/MemberWriteServiceTest.java
- 내 정보 수정 및 회원 탈퇴 작업
- 내 정보 수정 작업
- 내 정보 삭제 작업
- DTO record로 관리
- MemberReadService 및 MemberWriteService로 구분하기로 하여 의미없는 MemberService 삭제.
- 삭제에 따른 구조 변경
-
=> feat: 내 정보 수정

src/main/resources/application-dev.yml
- 자동으로 컬럼 Snake Case 변하도록 수정
- 
- 
-
=> fix: 자동 snake case로 변환

src/main/java/org/myteam/server/news/NewsDataInit.java, src/main/resources/application-dev.yml
=> fix: 뉴스 데이터 작업

src/main/resources/application-dev.yml
=> fix: ddl-auto 변경

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
=> fix: 뉴스 security설정 변경

src/main/java/org/myteam/server/board/dto/request/BoardServiceRequest.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/inquiry/controller/InquiryController.java, src/main/java/org/myteam/server/inquiry/dto/request/InquirySearchRequest.java, src/main/java/org/myteam/server/inquiry/dto/request/InquiryServiceRequest.java, src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java, src/main/java/org/myteam/server/inquiry/service/InquiryService.java, src/main/java/org/myteam/server/mypage/controller/MyPageController.java, src/main/java/org/myteam/server/mypage/service/MyPageReadService.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/inquiry/service/InquiryReadServiceTest.java, src/test/java/org/myteam/server/inquiry/service/InquiryServiceTest.java, src/test/java/org/myteam/server/member/service/MemberWriteServiceTest.java, src/test/java/org/myteam/server/mypage/service/MyPageReadServiceTest.java
=> fix: mock 빈과 실제 객체사이에서의 에러 해결

src/main/java/org/myteam/server/board/controller/BoardCommentController.java, src/main/java/org/myteam/server/board/repository/BoardCountLockRepository.java, src/main/java/org/myteam/server/board/repository/BoardCountRepository.java, src/main/java/org/myteam/server/board/service/BoardCommentService.java, src/main/java/org/myteam/server/board/service/BoardCountReadService.java, src/main/java/org/myteam/server/board/service/BoardCountService.java, src/main/java/org/myteam/server/board/service/BoardService.java
=> fix: readOnly 에러 해결

src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/service/MemberReadService.java
- 삭제된 멤버 조회하지 않는 코드 추가
- validateStatus 추가
- 
-
=> feat: findMember 수정

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/global/security/dto/CustomUserDetails.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/mypage/service/MyPageService.java, src/main/java/org/myteam/server/oauth2/service/CustomOAuth2UserService.java
=> fix: 비밀번호 필드 변경

src/main/java/org/myteam/server/board/domain/BoardCommentRecommend.java, src/main/java/org/myteam/server/board/domain/BoardCount.java, src/main/java/org/myteam/server/board/domain/BoardReplyRecommend.java
=> feat: 엔티티에 BaseTime 추가

src/main/java/org/myteam/server/board/domain/BoardCommentRecommend.java, src/main/java/org/myteam/server/board/domain/BoardRecommend.java, src/main/java/org/myteam/server/board/domain/BoardReplyRecommend.java
=> fix: 테이블을 설계 위한 수정

src/main/java/org/myteam/server/board/repository/BoardCommentRecommendRepository.java, src/main/java/org/myteam/server/board/repository/BoardReplyRecommendRepository.java, src/main/java/org/myteam/server/board/service/BoardCommentRecommendService.java, src/main/java/org/myteam/server/board/service/BoardReplyRecommendService.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/board/service/BoardCommentRecommendTest.java, src/test/java/org/myteam/server/board/service/BoardCountServiceTest.java, src/test/java/org/myteam/server/board/service/BoardReplyRecommendTest.java
- 
- 게시판 관련 추천 동시성 테스트 코드 작성 했습니다!
- 테스트코드 작성 중 수정할 부분도 함께 수정하면서 진행했습니다
- 
-
=> feat: 게시판 관련 추천 동시성 테스트 코드 작성

src/main/java/org/myteam/server/common/certification/controller/CertificationController.java, src/main/java/org/myteam/server/common/certification/domain/CertificationCode.java, src/main/java/org/myteam/server/common/certification/util/CertifyMailStrategy.java, src/main/java/org/myteam/server/common/certification/util/CertifyStorage.java, src/main/java/org/myteam/server/common/certification/util/TemporaryPasswordMailStrategy.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/service/MemberService.java
=> fix: 세션에 저장 안되는 문제 해결

src/main/java/org/myteam/server/auth/controller/AuthTestController.java, src/main/java/org/myteam/server/auth/controller/ReIssueController.java, src/main/java/org/myteam/server/common/certification/controller/CertificationController.java, src/main/java/org/myteam/server/common/mail/service/AbstractMailSender.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/service/CustomUserDetailsService.java, src/main/java/org/myteam/server/improvement/controller/ImprovementCommentController.java, src/main/java/org/myteam/server/improvement/controller/ImprovementController.java, src/main/java/org/myteam/server/improvement/controller/ImprovementRecommendController.java, src/main/java/org/myteam/server/improvement/controller/ImprovementReplyController.java, src/main/java/org/myteam/server/inquiry/controller/InquiryCommentController.java, src/main/java/org/myteam/server/inquiry/controller/InquiryController.java, src/main/java/org/myteam/server/inquiry/controller/InquiryReplyController.java, src/main/java/org/myteam/server/member/controller/AdminController.java, src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/mypage/controller/MyPageController.java, src/main/java/org/myteam/server/profile/controller/MemberProfileController.java
=> chore: swagger description 작성

src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java
=> fix: 필드 누락 해결

src/main/java/org/myteam/server/member/controller/MyInfoController.java, src/main/java/org/myteam/server/member/controller/response/MemberResponse.java
=> chore: @JsonIgnore 삭제

src/main/java/org/myteam/server/board/service/BoardService.java
=> feat: 게시글 조회수 증가 추가

src/main/java/org/myteam/server/board/controller/BoardController.java, src/main/java/org/myteam/server/board/service/BoardService.java
=> fix: 게시글 조회수 증가 에러 해결

src/main/java/org/myteam/server/improvement/dto/response/ImprovementCommentResponse.java, src/main/java/org/myteam/server/improvement/dto/response/ImprovementResponse.java, src/main/java/org/myteam/server/improvement/repository/ImprovementCommentQueryRepository.java, src/main/java/org/myteam/server/inquiry/dto/response/InquiryCommentResponse.java, src/main/java/org/myteam/server/inquiry/dto/response/InquiryDetailsResponse.java, src/main/java/org/myteam/server/inquiry/dto/response/InquiryReplyResponse.java, src/main/java/org/myteam/server/notice/Repository/NoticeCommentQueryRepository.java, src/main/java/org/myteam/server/notice/Repository/NoticeQueryRepository.java, src/main/java/org/myteam/server/notice/dto/response/NoticeCommentResponse.java, src/main/java/org/myteam/server/notice/dto/response/NoticeResponse.java
=> fix: maskedIp 적용

src/main/resources/application-dev.yml
=> fix: DB와 서버 시간 한국시간으로 수정

docker-compose.yml, src/main/java/org/myteam/server/ServerApplication.java
=> fix: 환경변수로 변경

src/main/java/org/myteam/server/news/newsCount/controller/NewsCountController.java
=> fix: 뉴스 카운트 에러 해결

src/main/java/org/myteam/server/board/dto/reponse/BoardDto.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java
- 전체 게시글 중 추천수가 높은 10개를 추천수 내림차순 > 조회수 + 댓글수 내림차순 > 게시글 제목 오름차순 > ID값 오름차순 으로 상위 10개만 isHot을 true로 내려줍니다.
- 게시판 목록 조회, 내가 쓴 게시글 목록 조회 H 뱃지 여부 응답값 추가
- 게시글 목록 조회 댓글 검색 결과 DTO 없을시 @JsonInclude(Include.NON_EMPTY) 추가 및 응답 필드명 변경
-
=> feat: 게시판 목록 조회, 내가 쓴 게시글 목록 조회 H 뱃지 여부 응답값 추가

src/main/java/org/myteam/server/inquiry/dto/request/InquiryFindRequest.java, src/main/java/org/myteam/server/inquiry/dto/request/InquirySearchRequest.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java
=> fix: dto 통일

src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/inquiry/dto/request/InquiryFindRequest.java, src/main/java/org/myteam/server/inquiry/dto/request/InquirySearchRequest.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java, src/main/java/org/myteam/server/news/newsComment/dto/repository/NewsCommentDto.java, src/main/java/org/myteam/server/news/newsComment/repository/NewsCommentQueryRepository.java, src/main/java/org/myteam/server/news/newsComment/service/NewsCommentService.java
=> fix: 뉴스 에러 대응

src/main/java/org/myteam/server/news/news/dto/controller/request/NewsRequest.java
=> chore: news dto 변경

src/test/java/org/myteam/server/news/news/controller/NewsControllerTest.java
=> chore: 테스트코드 수정

src/main/java/org/myteam/server/news/news/service/NewsReadService.java
- 뉴스 조회수 증가하도록 추가했습니다.,
- 뉴스조회 Service에addViewCount추가
- 
-
=> feat: 조회수 증가하도록 추가

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java
=> fix: 문의하기 page count 수정

src/main/java/org/myteam/server/board/dto/reponse/BoardCommentSearchDto.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java
=> fix: 댓글 검색 필터링 수정

src/main/java/org/myteam/server/global/exception/PlayHiveExceptionController.java
- IllegalArgumentException 예외발생시 AuthenticationEntryPointHandler 클래스로 빠져버려 401에러가 발생하여 ControllerAdvice에 추가
- 
- 
-
=> feat: IllegalArgumentException 발생시 ControllerAdvice에서 처리할수있도록 추가

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/improvement/controller/ImprovementCommentController.java, src/main/java/org/myteam/server/improvement/repository/ImprovementCommentQueryRepository.java, src/main/java/org/myteam/server/improvement/service/ImprovementCommentReadService.java, src/main/java/org/myteam/server/inquiry/controller/InquiryCommentController.java, src/main/java/org/myteam/server/inquiry/repository/InquiryCommentQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryCommentReadService.java, src/main/java/org/myteam/server/notice/controller/NoticeCommentController.java, src/main/java/org/myteam/server/notice/repository/NoticeCommentQueryRepository.java, src/main/java/org/myteam/server/notice/service/NoticeCommentReadService.java
- 공지사항, 개선요청 문의사항 베스트 댓글 조회입니다.
- 추천+최신순으로 세가지 댓글 내려주도록 구현하였습니다.
- 
-
=> feat: 공지사항, 개선요청, 문의사항 베스트 댓글 조회

src/main/java/org/myteam/server/news/newsComment/repository/NewsCommentQueryRepository.java
=> fix: 뉴스 베스트 댓글 수정

src/main/java/org/myteam/server/inquiry/dto/response/InquiryResponse.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java
=> fix: 문의하기 목록 조회시 maskedIp 적용

src/main/java/org/myteam/server/news/newsReply/domain/NewsReply.java, src/main/java/org/myteam/server/news/newsReply/dto/controller/request/NewsReplySaveRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/controller/request/NewsReplyUpdateRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/service/request/NewsReplySaveServiceRequest.java, src/main/java/org/myteam/server/news/newsReply/dto/service/request/NewsReplyUpdateServiceRequest.java, src/main/java/org/myteam/server/news/newsReply/service/NewsReplyService.java, src/test/java/org/myteam/server/IntegrationTestSupport.java, src/test/java/org/myteam/server/news/newsComment/service/NewsCommentServiceTest.java, src/test/java/org/myteam/server/news/newsReply/controller/NewsReplyControllerTest.java, src/test/java/org/myteam/server/news/newsReply/service/NewsReplyServiceTest.java
- 대댓글에서 멘션한 사람 publicid 받도록 수정했습니다.
- NewsReplyController에서 save, update 요청값에 추가했습니다.
- 
-
=> feat: 대댓글 멘션

src/main/java/org/myteam/server/game/repository/GameQueryRepository.java
=> fix: 페이징 버그 해결

src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/mypage/dto/request/MyPageRequest.java, src/main/java/org/myteam/server/mypage/dto/response/MyPageResponse.java, src/main/java/org/myteam/server/mypage/service/MyPageService.java
=> fix: 멤버 프로필 이미지 추가

src/main/java/org/myteam/server/board/service/BoardCommentService.java, src/main/java/org/myteam/server/board/service/BoardReplyService.java, src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/global/util/upload/MediaUtils.java, src/main/java/org/myteam/server/improvement/service/ImprovementCommentService.java, src/main/java/org/myteam/server/improvement/service/ImprovementReplyService.java, src/main/java/org/myteam/server/improvement/service/ImprovementService.java, src/main/java/org/myteam/server/inquiry/service/InquiryCommentService.java, src/main/java/org/myteam/server/inquiry/service/InquiryReplyService.java, src/main/java/org/myteam/server/notice/service/NoticeCommentService.java, src/main/java/org/myteam/server/notice/service/NoticeReplyService.java, src/main/java/org/myteam/server/notice/service/NoticeService.java, src/main/java/org/myteam/server/upload/config/S3ConfigAws.java, src/main/java/org/myteam/server/upload/config/S3ConfigLocal.java, src/main/java/org/myteam/server/upload/controller/S3Controller.java, src/main/java/org/myteam/server/upload/service/AwsS3Service.java, src/main/java/org/myteam/server/upload/service/LocalS3Service.java, src/main/java/org/myteam/server/upload/service/S3Service.java, src/main/java/org/myteam/server/upload/service/StorageService.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/java/org/myteam/server/IntegrationTestSupport.java
- AWS S3 버킷을 생성하고, CloudFront로 배포를 한 뒤, media.playhive.co.kr 도메인으로 설정도 완료하였습니다.
- 객체 접근할때에는 응답값으로 내려주는 download URL ex) https://media.playhive.co.kr/폴더명/파일명 로 접근 가능합니다.
- 현재 presignedURL 보안 상태는 아래와 같습니다! 
1) 로그인된 유저만 presignedURL 발급이 가능함
2) presignedURL은 생성 후 5분뒤면 만료
3) 다운로드시 도메인 설정
- AWS S3 작업
- active 설정에 따라 minIO s3(개발용), aws s3(운영용) 변경가능하도록 수정
- 
-
=> feat: 파일 업로드 AWS S3로 연결

src/main/java/org/myteam/server/comment/repository/CommentRepository.java, src/main/java/org/myteam/server/comment/service/CommentReadService.java, src/main/java/org/myteam/server/mypage/controller/MyPageController.java, src/main/java/org/myteam/server/mypage/dto/response/MyPageResponse.java, src/main/java/org/myteam/server/mypage/service/MyPageReadService.java, src/main/java/org/myteam/server/upload/config/S3ConfigLocal.java, src/main/java/org/myteam/server/upload/service/LocalS3Service.java
=> fix: 마이페이지 수정

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java
=> fix: 내 문의하기 목록 수정

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java
=> fix: 잘못된 조인 해결

src/main/java/org/myteam/server/improvement/controller/ImprovementRecommendController.java, src/main/java/org/myteam/server/improvement/repository/ImprovementQueryRepository.java, src/main/java/org/myteam/server/notice/controller/NoticeRecommendController.java, src/main/resources/application-test.yml
=> fix: 추천 컨트롤러 원복

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/match/match/domain/Match.java, src/main/java/org/myteam/server/match/match/domain/MatchCategory.java, src/main/java/org/myteam/server/match/match/repository/MatchQueryRepository.java, src/main/java/org/myteam/server/match/team/domain/Team.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- pathvariable에 자동으로 null로 들어갈걸 기대했는데 작동하지 않아 ALL로 받도록 하였습니다
- 
- 
-
=> fix: 경기일정 전체조회 버그 수정

src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/home/dto/HotBoardDto.java, src/main/java/org/myteam/server/home/dto/NewBoardDto.java
- 
- 실시간 HOT, NEW 게시글 목록 카테고리 타입, 이미지 여부 추가
- 
-
=> chore: 실시간 HOT, NEW 게시글 목록 카테고리 타입, 이미지 여부 추가

src/main/java/org/myteam/server/comment/controller/CommentController.java
=> chore: 댓글 API 기능 명시 추가

src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/board/service/BoardReadService.java, src/main/java/org/myteam/server/global/util/domain/TimePeriod.java, src/main/java/org/myteam/server/home/controller/HomeController.java, src/main/java/org/myteam/server/home/dto/TotalListResponse.java, src/main/java/org/myteam/server/home/dto/TotalSearchRequest.java, src/main/java/org/myteam/server/home/dto/TotalSearchServiceRequest.java, src/main/java/org/myteam/server/home/service/TotalReadService.java, src/main/java/org/myteam/server/news/news/dto/controller/request/NewsRequest.java, src/main/java/org/myteam/server/news/news/dto/service/request/NewsServiceRequest.java, src/main/java/org/myteam/server/news/news/repository/NewsQueryRepository.java, src/main/java/org/myteam/server/news/news/repository/TimePeriod.java, src/test/java/org/myteam/server/news/news/service/NewsReadServiceTest.java
- 통합 검색 개발하였습니다.
- 뉴스에서 동일하게 사용하는 것 통일하였고 메소드 DDD에 맞게 개발하였습니다
- Response 타입 제네릭을 사용하여 타입에 상관없이 진행하였습니다
- 뉴스 댓글에 대해서는 수정이 필요할 것 같습니다
-
=> feat: 통합 검색 개발

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/member/controller/response/MemberResponse.java, src/main/java/org/myteam/server/mypage/dto/response/MyPageResponse.java
=> fix: 이미지 필드 추가

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java
=> fix: inquiry prev

src/main/java/org/myteam/server/notice/repository/NoticeQueryRepository.java
=> fix: 보드에서 공지사항 조회시 필드 수정

src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java
=> fix: 실시간 HOT, 최신 게시글 목록 조회 시 이미지 존재 여부 버그 수정

src/main/java/org/myteam/server/comment/repository/CommentQueryRepository.java, src/main/java/org/myteam/server/comment/util/CommentFactory.java, src/main/java/org/myteam/server/global/exception/ErrorCode.java
=> fix: 댓글 생성, 조회 버그 수정

src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/global/config/RedisConfig.java, src/main/java/org/myteam/server/notice/service/NoticeReadService.java
=> fix: 잘못된 레디스 함수 참조

src/main/java/org/myteam/server/comment/controller/CommentController.java, src/main/java/org/myteam/server/comment/dto/response/CommentResponse.java, src/main/java/org/myteam/server/comment/repository/CommentQueryRepository.java, src/main/java/org/myteam/server/comment/service/CommentReadService.java, src/main/java/org/myteam/server/global/security/config/SecurityConfig.java
=> fix: best-comment 로직 ㅅ정

src/main/java/org/myteam/server/board/dto/reponse/BoardRankingDto.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/global/util/redis/RedisViewCountService.java
=> fix: 벌트 업데이트 수정, 게시글 isHot Redis에서 조회하는 로직 추가

src/main/java/org/myteam/server/global/exception/ErrorCode.java, src/main/java/org/myteam/server/inquiry/controller/InquiryController.java, src/main/java/org/myteam/server/inquiry/domain/Inquiry.java, src/main/java/org/myteam/server/inquiry/dto/request/InquiryRequest.java, src/main/java/org/myteam/server/inquiry/service/InquiryService.java
=> fix: 비로그인시 필드 추가

src/main/java/org/myteam/server/comment/domain/CommentType.java, src/main/java/org/myteam/server/comment/domain/MatchComment.java, src/main/java/org/myteam/server/comment/repository/CommentQueryRepository.java, src/main/java/org/myteam/server/comment/util/CommentFactory.java
=> chore: matchComment 추가

src/main/java/org/myteam/server/global/security/config/SecurityConfig.java, src/main/java/org/myteam/server/match/match/controller/MatchController.java, src/main/java/org/myteam/server/match/match/service/MatchReadService.java, src/test/java/org/myteam/server/match/match/controller/MatchControllerTest.java, src/test/java/org/myteam/server/match/match/service/MatchReadServiceTest.java
- API를 새로 만드는게 아니라 Generic 사용하여 응답값 유연하게 변하도록 수정했습니다
- 
- 
-
=> fix: generic 사용하여 기존 controller response 유연하게 바뀌도록 수정

src/main/java/org/myteam/server/inquiry/dto/response/InquiryResponse.java, src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java, src/main/java/org/myteam/server/inquiry/service/InquiryReadService.java
=> fix: 문의하기 댓글 검색시 에러 수정

src/main/java/org/myteam/server/inquiry/repository/InquiryQueryRepository.java
=> fix: 잘못된 where 절 추가

src/main/java/org/myteam/server/match/match/repository/MatchQueryRepository.java
- e스포츠 경기일정 오름차순으로 sorting
- 
- 
-
=> fix: e스포츠 경기일정 sort

src/main/java/org/myteam/server/oauth2/service/CustomOAuth2UserService.java
=> fix: 소셜 로그인 테스트중

src/main/java/org/myteam/server/global/util/cookie/CookieUtil.java
=> fix: 쿠키 도메인 변경

src/main/java/org/myteam/server/global/util/cookie/CookieUtil.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> fix: 서버 도메인 변경

src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> fix: 프론트 도메인으로 변경

src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> fix: 리다이렉트 url 변경

src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> fix: redirectUrl 변경

src/main/java/org/myteam/server/comment/controller/CommentController.java, src/main/java/org/myteam/server/comment/repository/CommentQueryRepository.java, src/main/java/org/myteam/server/comment/service/CommentReadService.java
=> fix: 댓글, 베스트 댓글 추천 여부 응답 에러 수정

src/main/java/org/myteam/server/member/service/MemberService.java, src/main/java/org/myteam/server/oauth2/controller/OAuthController.java, src/main/java/org/myteam/server/oauth2/dto/AddMemberInfoRequest.java, src/main/java/org/myteam/server/oauth2/handler/CustomOauth2SuccessHandler.java
=> feat: 소셜로그인 추가 정보 api 추가

src/main/java/org/myteam/server/board/service/BoardService.java, src/main/java/org/myteam/server/improvement/service/ImprovementService.java, src/main/java/org/myteam/server/notice/service/NoticeService.java
- 
- 작성/수정 시에는 조회수가 증가하지 않고 조회만 하도록 수정하였습니다.
- 
-
=> fix: 게시판, 공지사항, 개선요청 글 작성/수정 시 조회수 증가 제거

src/main/java/org/myteam/server/comment/repository/CommentQueryRepository.java
=> fix: 댓글 MATCH 버그 수정

src/main/java/org/myteam/server/global/security/filter/JwtAuthenticationFilter.java, src/main/java/org/myteam/server/global/security/service/CustomUserDetailsService.java, src/main/java/org/myteam/server/member/entity/Member.java, src/main/java/org/myteam/server/member/service/MemberService.java
=> fix: 에러 대응

src/main/java/org/myteam/server/inquiry/domain/InquiryOrderType.java
=> fix: 문의하기 목록 request 필드 추가

src/main/java/org/myteam/server/board/dto/reponse/BoardDto.java, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/home/controller/HomeController.java, src/main/java/org/myteam/server/home/dto/HotBoardDto.java, src/main/java/org/myteam/server/home/dto/NewBoardDto.java
=> chore: isNew 추가

src/main/java/org/myteam/server/comment/domain/CommentType.java, src/main/java/org/myteam/server/comment/repository/CommentQueryRepository.java
=> chore: 내가 쓴 댓글 목록 commentType ALL 추가

src/main/java/org/myteam/server/common/certification/util/TemporaryPasswordMailStrategy.java
=> fix: 로컬에서만 비밀번호 바꿀 수 있게

src/main/java/org/myteam/server/board/dto/request/BoardRequest.java
=> fix: 글자수 제한 추가

src/main/resources/templates/mail/certify-template.html, src/main/resources/templates/mail/signup-complete-template.html, src/main/resources/templates/mail/temporary-password-template.html
=> fix: 타임리프 css 변경

src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java
=> 실시간 HOT 게시글 목록 수정

.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml, .gitignore, build.gradle, monitoring/docker-compose.monitoring.yml, monitoring/prometheus.yml, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/resources/application.yml
=> 모니터링 도구 구축

docker-compose.yml, src/main/java/org/myteam/server/board/repository/BoardQueryRepository.java, src/main/java/org/myteam/server/home/dto/HotBoardDto.java
=> chore: 실시간 Hot 게시글 목록 조회 수정

src/main/java/org/myteam/server/global/util/redis/RedisService.java
- Redis만료시간이 분으로 되어있었네요 초로 바꿨습니다.
- 
- 
-
=> fix: 토큰 만료날짜 버그 수정

src/main/java/org/myteam/server/notice/dto/request/NoticeRequest.java
=> chore: 공지사항 제목 40자로 변경

src/main/resources/application.yml
=> chore: dev브랜치에서 active dev로 설정 변경
